name: Test Scraper No Proxies

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps
      
      - name: Test first city without proxies
        run: |
          # Create empty proxy file to avoid error
          touch formatted_proxies.txt
          
          # Run for first city only, no proxies
          python aa_hotels_scraper.py \
            --cities cities_top200.txt \
            --batch-start 0 \
            --batch-size 1 \
            --concurrent 1 \
            --no-proxy
          
          # Show results
          if [ -f cheapest_10k_hotels_by_city.csv ]; then
            echo "SUCCESS! Results:"
            cat cheapest_10k_hotels_by_city.csv
          else
            echo "No results file created"
          fi
          
          # Show any screenshots
          ls -la *.png || echo "No screenshots"
      
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            *.csv
            *.png
            *.log
